### PR TITLE
Update for running idempotently within CI/CD pipeline

### PR DESCRIPTION
**Pull request by irfancharania**
# Idempotent execution in CICD pipeline and other changes

- Idempotency improvements:
   - The generated SQL code now includes a T-SQL statement that idempotently creates the requisite `DiagramGeneration` schema.
   - The generated SQL code now uses a `CREATE OR ALTER PROCEDURE` statement instead of a `CREATE PROCEDURE` statement.
- Support added for the new `Encrypt` parameter found in new versions of the `SqlServer` PowerShell module.
- New version of `SqlServer` PowerShell module now required: `22.1.1` or higher.

### CODE REVIEW

**Comment by DanielLoth** [comment]
Hi @irfancharania. Thanks for the contribution.

**Comment by DanielLoth** [comment]
I get this issue locally when running the code in your branch.

image

**Comment by irfancharania** [comment]
Hi Daniel, I'm wondering if your SqlServer PowerShell module is older?
I'm currently successfully running this script with SqlServer module version "22.1.1" against SQL Server 2022.

Try:
``` powershell
Get-Module sqlserver -ListAvailable

Install-Module -Name SqlServer -AllowClobber
```

**Comment by DanielLoth** [comment]
Ah, good catch. Thanks.

**Comment by DanielLoth** [comment]
Alright, just finished testing this.

I was on Windows 11 and SQL Server 2022. Both terrible, so I had to revert my laptop to Windows 10 and SQL Server 2019.

Anyway, looks good to me.

**Review by DanielLoth — APPROVED** [review]

**Pull request merged**
